### PR TITLE
Convert package to ESM

### PR DESCRIPTION
**Pull request by itsMapleLeaf**
Converts the radix themes package to use ESM modules, changing tsconfigs and file extensions accordingly. The previous build was lacking .js file extensions, which breaks on tooling that adheres to Node's ESM spec.

Fixes https://github.com/radix-ui/themes/issues/77
Fixes https://github.com/radix-ui/themes/issues/51
Fixes https://github.com/radix-ui/themes/issues/13

Tested and works with the playground workspace, also tested in a personal Remix project

For other who need this fix, the package with these changes is available at [`@itsmapleleaf/radix-themes`](https://www.npmjs.com/package/@itsmapleleaf/radix-themes)

### CODE REVIEW

**Comment by marbemac** [comment]
❤️ 👍 this seems to be working in my setup (vite ssr setup).

**Comment by arminnaimi** [comment]
This is great. I am able to run this in a Astro site running v3.4.3. Thanks @itsMapleLeaf

**Comment by o-az** [comment]
Is there anything I can help with to get this pr merged?

**Comment by vladmoroz** [comment]
This is on our radar, but we'll need to carve out some time to take a close look and review. Appreciate the contribution ❤️

**Comment by smorimoto** [comment]
@vladmoroz Rather, this is essentially the packaging thing, and changing to ESM is not required. Of course, that is a more formal approach, but there is much simpler solution here: #158

**Comment by itsMapleLeaf** [comment]
> @vladmoroz Rather, this is essentially the packaging thing, and changing to ESM is not required. Of course, that is a more formal approach, but there is much simpler solution here: #158

From what I can tell, the other PR doesn't solve the issue that this one does, which is a problem that happens at _runtime_, due to Node ESM requiring explicit file extensions.

For example, take the file `dist/esm/index.js` emitted by the current build process, which is unchanged in the other PR:

```js
export { Theme, useThemeContext, updateThemeAppearanceClass } from './theme';
export * from './theme-options';
export * from './components';
export * from './helpers';
export { ThemePanel } from './theme-panel';
```

Even with `"type": "module"`, this will fail on Node, because the import paths don't have `.js` extensions.

It doesn't break in Next.js because Next.js uses webpack, which doesn't directly import the module, it bundles them, and doesn't care about extensions. But other tools, like Remix, Astro, SvelteKit, and probably most things based off of ESBuild or Vite, they emit JS files which `import "@radix-ui/themes"` as an external. Run that JS file, and boom: Node dies.

---

That being said, I considered tsup for this PR initially, but I wanted to keep the build system the same. Nonetheless, I gave tsup a try, and ran into issues.

Firstly, Next.js RSC expects separate files with separate `"use client"` and/or `"use server"` directives.

- If you bundle just the `index.ts` entry file, the directives get lost, and Next.js raises an error.
- If you treat every file as an entry, e.g. with `entry: ['src/**/*.{ts,tsx}']` the code gets moved to separate chunk files, and the directives don't go with them. Next.js raises an error.
- If you disable splitting, every entry file becomes its own bundle; same as the first issue, directives are lost, Next.js errors.
- If you disable bundling, you pretty much get a 1-to-1 source-to-dist output, but bundling also preserves the import strings. Runtime failure with Node ESM.

There's probably something you can do here to solve this (e.g. with some import rewriter plugin? and/or something that has more knowledge of `"use"` directives?) but tsup by itself doesn't seem to be able to fit the requirements.

---

All that being said, the `.js` extensions ensures that every environment is happy, more or less. Bundler or runtime.

**Comment by smorimoto** [comment]
In the case of native ESM, that is correct, but I assume that many users are probably in the Faux ESM environment, and in that case #158 is OK. For native ESM, this PR change is required for runtime indeed.

**Comment by itsMapleLeaf** [comment]
That's probably not a wrong assumption, but moving away from the ambiguous, problematic resolution rules of CommonJS is the more future-friendly move anyway, if nothing else to maximize environment compatibility.

**Comment by smorimoto** [comment]
No doubt. If maintainers can't take the time to review, it's not a bad idea to merge a simple PR first and then merge this PR. Does the Radix team have a clear timeline on this topic?

**Comment by smorimoto** [comment]
IS THERE ANYTHING I CAN DO TO MERGE THIS?! I want to get this really quickly.

**Comment by o-az** [comment]
@itsMapleLeaf for the Next.js "use server"/"use client", esbuild's plugin API is worth looking into. 
Specifically the [`onResolve`](https://esbuild.github.io/plugins/#on-resolve) & [`onBuild`](https://esbuild.github.io/plugins/#on-load) callbacks. [`tsup` has an `esbuild`](https://tsup.egoist.dev/#custom-esbuild-plugin-and-options) option.

**Comment by vladmoroz** [comment]
We are still investigating this and the adjacent areas. If you need this urgently your can always fork Radix Themes from this branch and release your own version temporarily.

**Comment by o-az** [comment]
> We are still investigating this and the adjacent areas. If you need this urgently your can always fork Radix Themes from this branch and release your own version temporarily.

I'm not currently using Radix. My first comment was when I attempted to use it in Astro a while back.

**Comment by vladmoroz** [comment]
@itsMapleLeaf @smorimoto thanks for your work, it was helpful for our initial iterations when testing in ESM and CJS projects. I'm closing this PR in favour of https://github.com/radix-ui/themes/pull/281.

We released `"@radix-ui/themes": "3.0.0-rc.1"` which should work in ESM projects if you need an early version now. Please refer to the changelog for other changes in this release.

**Comment by itsMapleLeaf** [comment]
Glad to see it! esbuild is definitely the better way to go over tsc 👍

**Pull request closed without merging**
